### ISSUE TITLE
Download page references download host, which is a redirect

### ISSUE THREAD

**Issue by Noki** [freifunk-berlin/berlin.freifunk.net#110]
https://berlin.freifunk.net/de/downloads/ and https://berlin.freifunk.net/en/downloads/ both reference https://download.berlin.freifunk.net/ as a location for eBooks, flyer and videos. The URL is a redirect and does not offer any of such downloads. This should be corrected or removed.

**Comment by FFHener** [comment]
According to archive.org, the old website had a [redirect](https://web.archive.org/web/20230223120712/http://download.berlin.freifunk.net/) to https://berlin.freifunk.net/download/ without an `s`. [There](https://web.archive.org/web/20230131004602/https://berlin.freifunk.net/download/) you could find a variety of (outdated) files.

**Comment by pktpls** [comment]
To keep the old /download URLs alive, we could have the webserver redirect only these specific subdirectories to some "archive" host. That way e.g. /download/attitude_adjustment would be available, while /download itself can still be a regular part of the new website.

**Comment by pktpls** [comment]
There's also https://download-master.berlin.freifunk.net/ which seems to be same directory content
