### ISSUE TITLE
deploy https for berlin.freifunk.net

### ISSUE THREAD

**Issue by booo** [freifunk-berlin/berlin.freifunk.net#19]
We should deploy https for berlin.freifunk.net

**Comment by cholin** [comment]
What is the status of this? @booo @egmont1227 ?

**Comment by booo** [comment]
@cholin I transfered the key/cert to @egmont1227. I'm in waiting state.

I actually think we should host the website on one of our vms. Setup and maintenance cost is minimal and the benefits e.g. flexibility, shared control/access are maximal.

**Comment by egmont1227** [comment]
Yes, we can host it on another Server / VM. But please dont put any more critical stuff on one Hardware-Host.

**Comment by booo** [comment]
@egmont1227 we should fix the configuration: 

https://www.ssllabs.com/ssltest/analyze.html?d=berlin.freifunk.net 

@cholin suggested this handbook: 

https://bettercrypto.org/static/applied-crypto-hardening.pdf

> But please dont put any more critical stuff on one Hardware-Host.

I do think the ball is for now in your court. We do not have an overview/documentation about the infrastructure, we do not have access to the machines, we do not have a concept for maintainership and an shared workflow.

I suggest the current core admins make some suggestions how we could work on the problems together. If spofs are part of the problem set we can work on this too.

**Comment by cholin** [comment]
Additionaly I would favor a permanent redirect from http to https!

**Comment by egmont1227** [comment]
@booo no problem, please send my the chipers-line for apache and i can insert it to conf-file. One done, i will redirect as suggested by @cholin

**Comment by booo** [comment]
@egmont1227 please try https://bettercrypto.org/static/configuration/Webservers/Apache/default-ssl as @cholin suggested. I don't have a tested configuration for apache.

**Comment by egmont1227** [comment]
done.

also see https://www.ssllabs.com/ssltest/analyze.html?d=berlin.freifunk.net

**Comment by cholin** [comment]
:+1:
