### ISSUE TITLE
howto on security enhancements in wireless mesh networks

### ISSUE THREAD

**Issue by booo** [freifunk-berlin/berlin.freifunk.net#30]
We should tell people how they can enhance thier security in wireless mesh networks and in networks in general.

Most import points are:
- ssl connections for e.g. mail clients (pointers to configuration examples)
- https connections for important http communication (https everywhere)
- anti tracking tools such as ghostery
- (advertisement blockers such as adblock)
- secure email communication (gpg)
- secure messenger communication (otr, and maybe other messangers textsecure?)

There is a project that is specialized on the topic. The project is called security in a box (https://securityinabox.org/). Maybe we can copy some parts and give proper attribution?

**Comment by carpodaster** [comment]
> There is a project that is specialized on the topic. The project is called security in a box (https://securityinabox.org/). Maybe we can copy some parts and give proper attribution?

I vote for this route. I'd say let's just link it (interwebs and stuff), but we probably never know when the ref goes 404. The [about page](https://securityinabox.org/about) says it's CC-BY-SA 3.0, so we should be fine copying contents. Let's not reinvent the wheel, there are already dozens of security-for-the-common-*man guides out there.

**Comment by sarumpaet** [comment]
There's
* https://wiki.freifunk.net/Berlin:Firmware#Ist_das_Netz_abh.C3.B6rsicher.3F
* https://wiki.freifunk.net/Sicherheit (linked to from the FAQ)

Please contribute there if anything's missing.
