### ISSUE TITLE
add TLWR710N to download page

### ISSUE THREAD

**Issue by booo** [freifunk-berlin/berlin.freifunk.net#32]
We should add WDR4900 and TLWR710N images to the http://berlin.freifunk.net/downloads/ page.

**Comment by andrenarchy** [comment]
... when the next stable firmware is released. ;)

**Comment by booo** [comment]
I added WDR4900.

**Comment by booo** [comment]
The WR710N is not a mainstream router and only used by a few individuals... I'm closing this for now.
