### ISSUE TITLE
list partnerships

### ISSUE THREAD

**Issue by booo** [freifunk-berlin/berlin.freifunk.net#34]
I suggest we create a list of partnerships we have and had in the past and add it to the website.

**Comment by booo** [comment]
Results from a short brain storming at the last hackathon:
```
Andreas-Gymnasium
BCIX e.V.
Beuth Hochschule
Bezirk Friedrichshain-Kreuzberg
Bezirk Neukölln
c-base
DK0TU
Deutsches Technik Museum Berlin
E-Lok
Flux.fm
Frauenhofer Instituts für XXX
Förderverein Freie Netzwerke e.V.
IN-Berlin
IPB
JUP
K9 (Hausprojekte)
MABB
Plattenvereinigung
ProfitBricks
Raumfahrt-Agentur
Syseleven
TODO Kirchen
Teufelsberg?
Wikimedia Deutschland
```

**Comment by sarumpaet** [comment]
This is probably quite difficult to maintain. It's difficult to say what entries are still valid already now, right? We should get permission to add them to the site before adding them - who's going to do that? Some of those will have logo guidelines etc... plus we already list them in the maps - perhaps some automated mechanism for showing some nodes more prominent would be in order instead.

Closing this for now, please reopen if necessary.
