### ISSUE TITLE
add a link to the github organisation

### ISSUE THREAD

**Issue by booo** [freifunk-berlin/berlin.freifunk.net#35]
We should add a link to the github organisation somewhere so people can for example find the firmware repository.

**Comment by cholin** [comment]
With d69beaa65e72833a16e10c9cd764a8904f07ef34 and ff2ccdada3ffaddc068a8c274b2876ee62d60827 I added links to our firmware repo and this repo as well.

**Comment by booo** [comment]
Thanks a lot. This looks great!
