### ISSUE TITLE
OpenWiFiMap

### ISSUE THREAD

**Issue by netnotix** [freifunk-berlin/berlin.freifunk.net#40]
Die OpenWifiMap ist mit dem OSM Layer nach kurzer Zeit unbrauchbar, weil Kacheln nicht mehr nachgeladen werden.
Hamburg zeigt, wie es besser geht (https://hamburg.freifunk.net/wo-wird-gefunkt)
Nach einem Wechsel ins Vollbild fehlt auch der Link zurück.

**Comment by booo** [comment]
Danke für deinen Hinweis. Aus meiner Sicht besteht zur Zeit kein Problem mit der Karte, deshalb schließe ich das Ticket. Falls wieder Probleme auftreten bitte das Ticket nochmal öffnen.
