### ISSUE TITLE
Add checksum of images to download page

### ISSUE THREAD

**Issue by slomo** [freifunk-berlin/berlin.freifunk.net#43]
The firmware has a feature that it displays the hashsum (md5 sha1???) of an update image. We should also offer it on the website.

**Comment by sarumpaet** [comment]
For integrity checking of downloads this would be okay.
For security/trust, detached PGP signatures would be better.
In any case, https://github.com/freifunk-berlin/buildbot/ is probably the place to go for this issue.

**Comment by sarumpaet** [comment]
See https://github.com/freifunk-berlin/util.berlin.freifunk.net/issues/2

**Comment by SvenRoederer** [comment]
Please check https://github.com/freifunk-berlin/buildbot/issues/54 regarding signing of images by using ucert / usign of OpenWrt
