### ISSUE TITLE
link to https:// for Mailinglist-archive

### ISSUE THREAD

**Issue by SvenRoederer** [freifunk-berlin/berlin.freifunk.net#47]
change the link on Mailman-Infopage  (https://lists.berlin.freifunk.net/cgi-bin/mailman/listinfo/berlin) to https-version. As site has working ssl-support

**Comment by booo** [comment]
Can you create a pull request for this? I think it's a good idea!

**Comment by SvenRoederer** [comment]
the link on the Mailman-page  is generated by runtime from the mailman config. So is this config avail via pupet?

**Comment by booo** [comment]
Ok, I get it. We should talk to @sarumpaet and nosy about this.

The certificate is for berlin.freifunk.net. We should create a certificate for lists.berlin.freifunk.net. I can create/request the certificate if need. I manage already a few certificates for *.berlin.freifunk.net.

**Comment by SvenRoederer** [comment]
indeed a matching Certificate will be needed for this subdomain. wondering why my browser did not complain on this mismatch

**Comment by booo** [comment]
@SvenRoederer can you maybe contact nosy and @sarumpaet via mail and put me in cc? I can create/request the certificate. I think it's a good idea collect the certs all at one place.

**Comment by sarumpaet** [comment]
I'll have a look soon.

**Comment by SvenRoederer** [comment]
for me these settings did it
DEFAULT_URL_PATTERN
PUBLIC_ARCHIVE_URL =

**Comment by sarumpaet** [comment]
The list config interface is HTTPS only now; the archive is HTTP and HTTPS (doesn't make much sense to require HTTPS for something that's completely public).

**Comment by booo** [comment]
Thanks for tackling the problem!

If we want to take a bold step into the future I think we should try to require HTTPS in every situation. To stick with the example nobody but the server should be able to see what I'm most interested in.

**Comment by sarumpaet** [comment]
Oh well, done. Another horse dead.
