### ISSUE TITLE
Maps are down

### ISSUE THREAD

**Issue by kpufahl** [freifunk-berlin/berlin.freifunk.net#52]
"Karte" and "Knoten" are not shown. The first is empty, the latter gives error "Fehler beim Laden der Daten".

**Comment by SvenRoederer** [comment]
looks like @andrenarchy is hunting for this ...
https://lists.berlin.freifunk.net/pipermail/berlin/2016-June/033355.html

**Comment by andrenarchy** [comment]
fixed

**Comment by booo** [comment]
Danke!
