### ISSUE TITLE
pls add Kiezliste für Spandau to https://berlin.freifunk.net/contact/

### ISSUE THREAD

**Issue by bobster-galore** [freifunk-berlin/berlin.freifunk.net#56]
<li>
    <a href="https://www.geroedel.de/mailman/listinfo/ff-spandau" class="externalLink">Berlin Spandau</a>
    <i>Kiezliste f&uuml;r Spandau</i>
  </li>

**Comment by SvenRoederer** [comment]
can you create a PR for this? (like https://github.com/freifunk-berlin/berlin.freifunk.net/commit/ebe54c9a6ed404af38fdfcd7d981744b86274997)

thanks :-)
