### ISSUE TITLE
Kiezbuero_Gelbhaar

### ISSUE THREAD

**Issue by PeterJo123** [freifunk-berlin/berlin.freifunk.net#61]
Die Adresse, unter der der Knotenpunkt eingetragen ist, ist richtig (Prenzlauer Allee 22), da  kann ihn sehen. Auf der Karte ist er jedoch auf dem Kampus Nord der HU zu finden. Ist das vielleicht veraltet?

LG Joachim

**Comment by bobster-galore** [comment]
Offensichtlich ist da was veraltet. Vielleicht einfach die Routerkoordinaten umstellen auf die Prenzlauer Allee 22.
ru bob

**Comment by sarumpaet** [comment]
Die Knotendaten werden in der Firmware/Config-Overfläche des jeweiligen Knotens gesetzt.
Am besten ggf. beim angegebenen Kontakt anfragen.
https://util.berlin.freifunk.net/knoteninfo?knoten=kiezbuero_gelbhaar
