### ISSUE TITLE
update nodecount in berlin.json

### ISSUE THREAD

**Issue by SvenRoederer** [freifunk-berlin/berlin.freifunk.net#65]
In the past someone updated the nodecount of the berlin.json file to have recent data showing up in the freifunk-api (https://github.com/freifunk-berlin/berlin.freifunk.net/commits/master/www/static/berlin.json). The last update was done in Sept. 2019 and as the user is just "Freifunk Berlin" it seems the user removed its github-account and stopped updating.

We should update this again and probably automate this. "GitHub Actions" might be an way to got. Before thinking of updating: 
What's the official source of the nodes-count? Hopglass or OWM? OWM is know to be unstable and gives sometimes "HTTP 500-errors"; hopglass somehow relies on OWM and also shows a low nodescount when OWM is down.

**Comment by sarumpaet** [comment]
That ^ updates from Hopglass via the Makefile which is called every hour. Hopglass count is off if OWM is down but that will be fixed at some point.

**Comment by SvenRoederer** [comment]
shouldn't we also update the "lastchange" field with something link ```date -u +%FT%TZ``` (2020-05-08T15:45:09Z)?

**Comment by sarumpaet** [comment]
see 0b49e83

**Comment by SvenRoederer** [comment]
Also had seen "date --iso-8601=seconds", but as there isn't a timezone in it I'm note sure about it.

**Comment by SvenRoederer** [comment]
But the website show that it works, so the parser of the file seems to be not totally confused.
