### ISSUE TITLE
Donate: Firefox does not show content of betterplace-page

### ISSUE THREAD

**Issue by Akira25** [freifunk-berlin/berlin.freifunk.net#68]
Apparently, betterplace configured, that their site cannot be embedded into other pages. See this screenshot:

![Screenshot_20200726_145547](https://user-images.githubusercontent.com/43141307/88479589-87267800-cf50-11ea-9555-a0e3735941c2.png)

The Firefox suggests to open that page in another tab. This solution might be safe, but does not look nice. Is there another way of including betterplace.org?

**Comment by SvenRoederer** [comment]
on https://www.betterplace.org/c/hilfe/link-zu-betterplace they refer to different tools for linking. But it seems managing them is up to the "project-manager" ????

Btw. I did not found a "Freifunk-Berlin" project at betterplace at all. The "best" match is https://www.betterplace.org/c/hilfe/link-zu-betterplace of the Förderverein Freie Netzwerke e.V.  @monic2001

**Comment by egmont1227** [comment]
scheint wieder zu gehen

![image](https://user-images.githubusercontent.com/4333752/97159350-06f3f680-177b-11eb-9445-567e07617789.png)
