### ISSUE TITLE
Linkfix https://berlin.freifunk.net/participate/overview/

### ISSUE THREAD

**Issue by Wnme** [freifunk-berlin/berlin.freifunk.net#79]
A link on https://berlin.freifunk.net/participate/overview/ is broken.

Current target https://wiki.freifunk.net/Berlin:Firmware/Howto is invalid. Need to be fixed to https://wiki.freifunk.net/Berlin:Firmware/HowTo

**Comment by Akira25** [comment]
Thank you a lot for reporting this! From the code side this should have been fixed some time ago:

https://github.com/freifunk-berlin/berlin.freifunk.net/blob/4c54ba73bfe1e52d9436dee000749aad949b7766/www/participate/overview.html#L61

But the deployed version on the website still points to the link with the typo. I will do some further research on this.

**Comment by Akira25** [comment]
The deployment got fixed. There was some strange error with a git pull on a strange ssh-port. This was switched to pull via https and now it works again.

Thank you for spotting this issue.
