### ISSUE TITLE
Make website responsive

### ISSUE THREAD

**Issue by Akira25** [freifunk-berlin/berlin.freifunk.net#80]
Reading the website on mobile devices is fairly difficult, as it doesn't scale for tiny displays. The website should be modified, so that it supports responsive design. 

This can either happen by including the bootstrap-responsive CSS and making some modifications to the structure to enable better floating

or by having a more sophisticated rework.

Currently the website uses bootstrap-2.3.2

**Comment by Noki** [comment]
The static website sitemap generator is really outdated and not well maintained. I suggest migrating over to https://gohugo.io/ and customize the colors of a suitable, minimalistic template.

**Comment by FFHener** [comment]
Will be fixed by #85
