### ISSUE TITLE
Renovate website

### ISSUE THREAD

**Issue by noxilixon** [freifunk-berlin/berlin.freifunk.net#85]
The website should be renovated so that it is up to date and an easy entrance for new users.

Criteria we already collected:

- Mobile friendly
- Bilingual (DE/EN)
- Hugo based
- Moving the docs from wiki to website
- Remove old docs

_This was discussed on the [community day 16.9.23](https://github.com/freifunk-berlin/meta/blob/main/protokolle/2023-09-16.md)_

**Comment by Noki** [comment]
Once #84 is merged, we should go over the things discussed here and create issues so we can keep track of the tasks.

**Comment by noxilixon** [comment]
I have tried to reflect the open points and discussions I have seen here in the chat in the [new issues](https://github.com/freifunk-berlin/berlin.freifunk.net/labels/Hugo%20Website).

**Comment by noxilixon** [comment]
I did not create a issue for

> location data available as machine parseable data (i.e., location pages have their table data available programmatically at https://wiki.freifunk.net/Spezial:Durchsuchen/:Berlin:Standorte:Alboinkontor etc.)

because I would do it the other way around, as proposed in #97. The data should be available as JSON (at a place to be decided), and the website should pull this data and use it to build the location page.

**Comment by noxilixon** [comment]
As far as I can see the different points of this discussion are in separated issues now.
